#!/bin/sh

cd `dirname $0`

#g++ -g -Os ./sources/*.cpp -I ./headers -o bin/Projet
#i586-mingw32msvc-g++ ./sources/*.cpp -I ./headers -o bin/Projet.exe

if test ! -e Makefile; then
	./autogen.sh
	./configure
fi

make -j 5
